### PR TITLE
Transactions should go to error state if they revert

### PR DESCRIPTION
**Pull request by tyler17**
If the `status` field in the transaction receipt is 0, it means that the transaction reverted.

I still need to merge this with the integration test work, but it looks like that isn't passing travis so am holding off on that for now.

### CODE REVIEW

**Comment by levity** [comment]
Ethan’s merge to dev is ok—it’s just my branch that’s failing

**Comment by levity** [comment]
Great, sounds good. I'll check it out locally if I have time. That error
event listener test is really touchy. There must be something I'm missing
about the interactions there.

**Comment by levity** [comment]
I can reproduce the issue. Let's wait until I merge #48 though before searching for a fix, because I made some changes to the that test file there to address a similar error. In the meantime you can go ahead and add an out-of-gas test.

**Comment by tyler17** [comment]
Sounds good.  I just pushed a test for out of gas (two kinds, one where the base limit is exceeded, and one where it isn't), and a test for not enough ether (though its commented out for now).

It looks like the weird jest issues aren't specific to that `error event listener` test.  The tests I aded after the revert transaction test fail for inexplicable reasons (one because it throws the error from the previous test, one because three expect statements are fulfilled even though there are only 2 in the test, and one due to a nonce issue).  So there's definitely an issue with code from tests running during other tests.  All the tests pass when run individually.

**Comment by levity** [comment]
Ok! I think what I’ll do is merge your changes into my branch, fix any
conflicts there, then merge everything to dev at once.

**Comment by levity** [comment]
Merged with #48

**Pull request closed without merging**
