### PR TITLE
create basic typings file for dai-plugin-mcd

### PR DESCRIPTION
**Pull request by levity**

### CODE REVIEW

**Review by jparklev — APPROVED** [review]

**Comment by jparklev** [comment]
Is this to eliminate the ts warnings from importing dai plugin mcd?

**Comment by levity** [comment]
so, i created this to resolve #249, and it does make the reported error (which i see in VS Code) go away. but i don't know if it breaks multicall watch interface typings. i don't see why it would, but i'm still pretty inexperienced with TS declaration files.

@Padraic-O-Mhuiris i'm tagging you as a reviewer on this because at this point you have the most familiarity with the way the existing typings for multicall in dai-plugin-mcd behave, so maybe you'll see something i don't.

@michaelelliot you are welcome to comment as well but of course only if you want to.

**Comment by michaelelliot** [comment]
@levity Just tested it and the multicall typings still work.

One way to quickly test it in VSCode after making changes (and building/pushing the `dai-plugin-mcd` changes with `yalc publish -p`) is to run `TypeScript: Restart TS server` from the command palette in the `mcd-cdp-portal` project.

**Comment by levity** [comment]
Cool, and thanks for the tip!

**Pull request merged**
